markdown: rdiscount

permalink: /:title/

#url: http://jason-zhuo.github.io/
name:         Jaosonzhuo's blog
description:  Jasonzhuo's blog
url:          http://jasonzhuo.com/


email: jason_zhuo@iclould.com
github: jason-zhuo
weibo: zhuozhongliu316

highlighter: pygments
#pygments: true

excerpt_separator: <!-- more -->

paginate: 8

about: "About me。"

