markdown: rdiscount

permalink: /:title/

url: http://jason-zhuo.github.io/

name: Jaosonzhuo's Blog
author: Jaosonzhuo
description: "Jasonzhuo的博客"

email: zhongiu.zhuo@gmail.com
youyan: cubernetgithub
github: jason-zhuo
weibo: zhuozhongliu316

pygments: true

excerpt_separator: <!-- more -->

paginate: 8

about: "About me。"